[workspace]

members = [ "critique2boxd", "critique_api", "critique_random" ]
resolver = "2"

[workspace.dependencies]
clap = { version = "4.5.1", features = ["derive"] }
color-eyre = "0.6.2"
critique_api = { path = "../critique_api" }
rand = "0.9.2"
csv = "1.3.0"
serde = "1.0.196"
