[package]
name = "critique_website"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = "0.7.0-rc.0"
js-sys = "0.3.77"
critique_api = { path = "../critique_api" }

[features]
default = ["web"]
web = ["dioxus/web"]
